apiVersion: v1
kind: ConfigMap
metadata:
  name: case-management-service-config
  labels:
    app: case-management-service
data:
  PORT: "8082"
  GCP_PROJECT_ID: "mltf-506212"
  GCP_SPANNER_INSTANCE_ID: "mltf-spanner"
  GCP_SPANNER_DATABASE_ID: "mortgage_db"
